/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\models\air_conditioner.glb -t -o src\components\AirConditioner.tsx 
*/

import * as THREE from 'three'
import type { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Conditioner: THREE.Mesh
    Line017: THREE.Mesh
    Line018: THREE.Mesh
    Line019: THREE.Mesh
    Line020: THREE.Mesh
    Line021: THREE.Mesh
    Line022: THREE.Mesh
    Line023: THREE.Mesh
    Line024: THREE.Mesh
    Line025: THREE.Mesh
    Line026: THREE.Mesh
    Line027: THREE.Mesh
    Line028: THREE.Mesh
    Line029: THREE.Mesh
    Line030: THREE.Mesh
    Line031: THREE.Mesh
    Line032: THREE.Mesh
    Line033: THREE.Mesh
    Line034: THREE.Mesh
    Line035: THREE.Mesh
    Line036: THREE.Mesh
    Line037: THREE.Mesh
    Line038: THREE.Mesh
    Line039: THREE.Mesh
    Line040: THREE.Mesh
    Line041: THREE.Mesh
    Line042: THREE.Mesh
    Line043: THREE.Mesh
    Line044: THREE.Mesh
    Line045: THREE.Mesh
    Line046: THREE.Mesh
    Line047: THREE.Mesh
    Object013: THREE.Mesh
    Shape001: THREE.Mesh
  }
  materials: {
    ['01 - Default']: THREE.MeshStandardMaterial
    ['14 - Default']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/air_conditioner.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      {/* posisi grup di-nolkan agar AC terpusat di titik asal komponen */}
      <group position={[0, 0, 0]} scale={0.025}>
        <mesh geometry={nodes.Conditioner.geometry} material={materials['01 - Default']} position={[0, -5.611, -0.054]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.394} />
        <mesh geometry={nodes.Line017.geometry} material={materials['01 - Default']} position={[-14.328, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line018.geometry} material={materials['01 - Default']} position={[-13.352, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line019.geometry} material={materials['01 - Default']} position={[-12.376, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line020.geometry} material={materials['01 - Default']} position={[-11.4, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line021.geometry} material={materials['01 - Default']} position={[-10.424, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line022.geometry} material={materials['01 - Default']} position={[-9.448, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line023.geometry} material={materials['01 - Default']} position={[-8.472, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line024.geometry} material={materials['01 - Default']} position={[-7.496, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line025.geometry} material={materials['01 - Default']} position={[-6.52, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line026.geometry} material={materials['01 - Default']} position={[-5.544, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line027.geometry} material={materials['01 - Default']} position={[-4.568, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line028.geometry} material={materials['01 - Default']} position={[-3.592, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line029.geometry} material={materials['01 - Default']} position={[-2.616, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line030.geometry} material={materials['01 - Default']} position={[-1.64, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line031.geometry} material={materials['01 - Default']} position={[-0.664, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line032.geometry} material={materials['01 - Default']} position={[0.312, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line033.geometry} material={materials['01 - Default']} position={[1.288, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line034.geometry} material={materials['01 - Default']} position={[2.264, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line035.geometry} material={materials['01 - Default']} position={[3.24, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line036.geometry} material={materials['01 - Default']} position={[4.216, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line037.geometry} material={materials['01 - Default']} position={[5.192, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line038.geometry} material={materials['01 - Default']} position={[6.167, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line039.geometry} material={materials['01 - Default']} position={[7.143, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line040.geometry} material={materials['01 - Default']} position={[8.119, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line041.geometry} material={materials['01 - Default']} position={[9.095, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line042.geometry} material={materials['01 - Default']} position={[10.071, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line043.geometry} material={materials['01 - Default']} position={[11.051, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line044.geometry} material={materials['01 - Default']} position={[12.031, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line045.geometry} material={materials['01 - Default']} position={[13.011, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line046.geometry} material={materials['01 - Default']} position={[13.99, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Line047.geometry} material={materials['01 - Default']} position={[14.97, -3.879, 1.755]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Object013.geometry} material={materials['14 - Default']} position={[0, -5.611, -0.054]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.394} />
        <mesh geometry={nodes.Shape001.geometry} material={materials['01 - Default']} position={[0, -5.611, -0.054]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.394} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/air_conditioner.glb')
