/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import type { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    accent_cabinet_pfo_bsw: THREE.Mesh
  }
  materials: {
    accent_cabinet_Mat: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/credenza.glb') as unknown as GLTFResult
  // Material asli punya normal map "cane/rattan" yang bikin permukaan tampak
  // ber-anyam kasar. Pakai material baru: pertahankan warna baseColor, BUANG
  // normal map -> permukaan halus tapi warna/panel tetap.
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.accent_cabinet_pfo_bsw.geometry} castShadow receiveShadow>
        <meshStandardMaterial map={materials.accent_cabinet_Mat.map} roughness={0.85} metalness={0} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/credenza.glb')
