/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import type { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    accent_cabinet_pfo_bsw: THREE.Mesh
  }
  materials: {
    accent_cabinet_Mat: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/credenza.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.accent_cabinet_pfo_bsw.geometry}
        material={materials.accent_cabinet_Mat}
        castShadow
        receiveShadow
      />
    </group>
  )
}

useGLTF.preload('/models/credenza.glb')
