/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import type { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
type GLTFResult = GLTF & {
  nodes: {
    Cube157: THREE.Mesh
    Cube157_1: THREE.Mesh
    Cube157_2: THREE.Mesh
  }
  materials: {
    Door_colors: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    Hinge: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/models/uploads_files_3300784_Door1_001.glb') as unknown as GLTFResult
  // baseColorTexture bawaan pintu ("Douglas Fir white") tampak ber-anyam/grid
  // pada skala UV ini (bukan efek kompresi — ada di asset aslinya). Ganti
  // material panel pintu dengan warna solid bersih (seperti pintu dicat).
  return (
    <group {...props} dispose={null}>
      {/* panel pintu — warna solid bersih */}
      <mesh castShadow receiveShadow geometry={nodes.Cube157.geometry}>
        <meshStandardMaterial color="#d8d3c8" roughness={0.8} metalness={0} />
      </mesh>
      {/* HANDLE pintu — hitam metalik */}
      <mesh castShadow receiveShadow geometry={nodes.Cube157_1.geometry}>
        <meshStandardMaterial color="#141414" roughness={0.4} metalness={0.6} />
      </mesh>
      {/* ENGSEL pintu — hitam metalik */}
      <mesh castShadow receiveShadow geometry={nodes.Cube157_2.geometry}>
        <meshStandardMaterial color="#141414" roughness={0.4} metalness={0.6} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/uploads_files_3300784_Door1_001.glb')
