/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import type { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { useLayoutEffect,useRef } from 'react'
type GLTFResult = GLTF & {
  nodes: {
    Cube157: THREE.Mesh
    Cube157_1: THREE.Mesh
    Cube157_2: THREE.Mesh
  }
  materials: {
    Door_colors: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    Hinge: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials,scene } = useGLTF('/models/uploads_files_3300784_Door1_001.glb') as unknown as GLTFResult
  useLayoutEffect(() => {
    if (scene) {
      const box = new THREE.Box3().setFromObject(scene);
      const size = new THREE.Vector3();
      box.getSize(size);

      console.log('Model Door Size:', size); // size will contain x, y, z dimensions
    }
  }, [scene]);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube157.geometry}
        material={materials.Door_colors}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube157_1.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube157_2.geometry}
        material={materials.Hinge}
      />
    </group>
  )
}

useGLTF.preload('/models/uploads_files_3300784_Door1_001.glb')
