/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useMemo } from 'react'
import type { JSX } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Legs: THREE.SkinnedMesh
    Monitor: THREE.SkinnedMesh
    MonitorScreen: THREE.SkinnedMesh
    Bone: THREE.Bone
  }
  materials: {
    Monitor: THREE.MeshStandardMaterial
    Screen: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { scene } = useGLTF('/models/monitor.glb')
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Bone} />
      <skinnedMesh geometry={nodes.Legs.geometry} material={materials.Monitor} skeleton={nodes.Legs.skeleton} castShadow />
      <skinnedMesh geometry={nodes.Monitor.geometry} material={materials.Monitor} skeleton={nodes.Monitor.skeleton} castShadow />
      <skinnedMesh geometry={nodes.MonitorScreen.geometry} material={materials.Screen} skeleton={nodes.MonitorScreen.skeleton} />
    </group>
  )
}

useGLTF.preload('/models/monitor.glb')
