/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: LagzDesign (https://sketchfab.com/LagzDesign)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-mouse-free-low-poly-47f83a631bdc48fcb76e530f5cde3f07
Title: Gaming Mouse - Free low poly
*/

import * as THREE from 'three'
import type { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
  }
  materials: {
    Main: THREE.MeshStandardMaterial
    Metalic: THREE.MeshStandardMaterial
    Accent: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/mouse.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Main} castShadow receiveShadow />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Metalic} castShadow />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Accent} castShadow />
      <mesh geometry={nodes.Object_7.geometry} material={materials.material} castShadow />
    </group>
  )
}

useGLTF.preload('/models/mouse.glb')
