/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\models\plant.glb -t -o src\components\Plant.tsx 
*/

import * as THREE from 'three'
import type { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    gul00: THREE.Mesh
    gul00_1: THREE.Mesh
    gul00_2: THREE.Mesh
    gul00_3: THREE.Mesh
  }
  materials: {
    cordyline_glauca_dirt: THREE.MeshPhysicalMaterial
    cordyline_glauca_leaf: THREE.MeshPhysicalMaterial
    cordyline_glauca_stem: THREE.MeshPhysicalMaterial
    cordyline_glauca_vase: THREE.MeshPhysicalMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/plant.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.gul00.geometry} material={materials.cordyline_glauca_dirt} />
      <mesh geometry={nodes.gul00_1.geometry} material={materials.cordyline_glauca_leaf} />
      <mesh geometry={nodes.gul00_2.geometry} material={materials.cordyline_glauca_stem} />
      <mesh geometry={nodes.gul00_3.geometry} material={materials.cordyline_glauca_vase} />
    </group>
  )
}

useGLTF.preload('/models/plant.glb')
