/*
Auto-generated by: https://github.com/pmndrs/gltfjsx (sofa baru)
Dibersihkan: hapus import React & PerspectiveCamera, path /models, cast,
castShadow/receiveShadow. Material per-node (model tak punya nama material).
Model kecil (~0.067 unit), jadi di Room dipakai scale besar (~19).
*/

import * as THREE from 'three'
import type { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Sphere001: THREE.Mesh
    Sphere002: THREE.Mesh
    Sphere003: THREE.Mesh
    Sphere004: THREE.Mesh
    Sphere005: THREE.Mesh
    Sphere006: THREE.Mesh
    Plane003: THREE.Mesh
    Plane004: THREE.Mesh
    w: THREE.Mesh
    Shape003: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder003: THREE.Mesh
    Cylinder004: THREE.Mesh
    Cylinder002: THREE.Mesh
    Shape004: THREE.Mesh
    Shape005: THREE.Mesh
    w002: THREE.Mesh
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/models/sofa.glb') as unknown as GLTFResult
  const meshes = [
    nodes.Sphere001, nodes.Sphere002, nodes.Sphere003, nodes.Sphere004,
    nodes.Sphere005, nodes.Sphere006, nodes.Plane003, nodes.Plane004,
    nodes.w, nodes.Shape003, nodes.Cylinder001, nodes.Cylinder003,
    nodes.Cylinder004, nodes.Cylinder002, nodes.Shape004, nodes.Shape005,
    nodes.w002,
  ]
  return (
    <group {...props} dispose={null}>
      <group scale={0.001}>
        <group position={[-0.151, 2.081, 1.667]}>
          {meshes.map((m, i) => (
            <mesh key={i} geometry={m.geometry} material={m.material} castShadow receiveShadow />
          ))}
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/sofa.glb')
