/*
Auto-generated by: https://github.com/pmndrs/gltfjsx (TCL 50" TV)
*/

import * as THREE from 'three'
import type { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    TCL_LOGO: THREE.Mesh
    Mesh001: THREE.Mesh
    Mesh001_1: THREE.Mesh
    Mesh001_2: THREE.Mesh
    Mesh001_3: THREE.Mesh
  }
  materials: {
    Chrome_Logo: THREE.MeshStandardMaterial
    Edge_Screen: THREE.MeshStandardMaterial
    screen: THREE.MeshStandardMaterial
    Back_Cap: THREE.MeshStandardMaterial
    Base: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/tv.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.TCL_LOGO.geometry} material={materials.Chrome_Logo} castShadow />
      <mesh geometry={nodes.Mesh001.geometry} material={materials.Edge_Screen} castShadow />
      <mesh geometry={nodes.Mesh001_1.geometry} material={materials.screen} />
      <mesh geometry={nodes.Mesh001_2.geometry} material={materials.Back_Cap} castShadow />
      <mesh geometry={nodes.Mesh001_3.geometry} material={materials.Base} castShadow />
    </group>
  )
}

useGLTF.preload('/models/tv.glb')
